---
# tasks file for grafana_installer

- name: Install grafana
  include_tasks: install.yml
  when: >
    (( grafana_install | bool ) and ( ansible_distribution == "RedHat" and ansible_distribution_major_version == '7' ))
    or
    (( grafana_install | bool ) and ( ansible_distribution == "CentOS" and ansible_distribution_major_version == '7' ))

- name: Uninstall grafana
  include_tasks: uninstall.yml
  when: >
    (( not grafana_install | bool ) and ( ansible_distribution == "RedHat" and ansible_distribution_major_version == '7' ))
    or
    (( not grafana_install | bool ) and ( ansible_distribution == "CentOS" and ansible_distribution_major_version == '7' ))

