{
 "title": "AlertManager",
 "time": { "from": "2019-04-26T03:59:57.392Z", "to": "2019-04-26T09:59:57.392Z" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ExporterDown",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "alertname=ExporterDown", "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Linux CpuLoad",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "alertname=CpuLoad", "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Linux Memory(>85%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "alertname=Memory", "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Linux Swap Used(>75%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "alertname=Swap Used", "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Linux Filesystem Space Used(>80%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Filesystem Space Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Linux Filesystem Inodes Used(>85%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Filesystem Inodes Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Linux Process Open Files Used(>85%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Process Open Files Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Linux UnusualNetworkThroughputIn(>100 MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=UnusualNetworkThroughputIn",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Linux UnusualNetworkThroughputOut(>100 MB/s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=UnusualNetworkThroughputOut",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Windows Nodes Disk Used(>80%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Windows Nodes Disk Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Windows Nodes CPU Used(>90%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Windows Nodes CPU Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Windows Nodes Memory Used(>85%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Windows Nodes Memory Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Windows Nodes Virtual Memory Used(>75%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Windows Nodes Virtual Memory Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Windows Nodes Net utilization Used(>90%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=Windows Nodes Net utilization Used",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "node_exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "ExporterDown",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "alertname=ExporterDown",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "CpuLoad",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "alertname=CpuLoad",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "alertname=Memory",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Swap Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "alertname=Swap Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Filesystem Space Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "alertname=Filesystem Space Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Filesystem Inodes Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "alertname=Filesystem Inodes Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Process Open Files Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "alertname=Process Open Files Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "UnusualNetworkThroughputIn",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "alertname=UnusualNetworkThroughputIn",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "UnusualNetworkThroughputOut",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 130 },
     "targets": [
      {
       "expr": "alertname=UnusualNetworkThroughputOut",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    }
   ]
  },
  {
   "title": "wmi_exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Windows Nodes Disk Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "alertname=Windows Nodes Disk Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Windows Nodes CPU Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "alertname=Windows Nodes CPU Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Windows Nodes Memory Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "alertname=Windows Nodes Memory Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Windows Nodes Virtual Memory Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "alertname=Windows Nodes Virtual Memory Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Windows Nodes Net utilization Used",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "alertname=Windows Nodes Net utilization Used",
       "labelSelector": "*",
       "legendFormat": "{{msg}}",
       "target": "Query",
       "type": "table"
      }
     ]
    }
   ]
  }
 ]
}