{
 "title": "Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "alias", "label": "hostname", "query": "label_values(up,alias)" },
   { "name": "env_type", "label": "env_type", "query": "label_values(up,env_type)" },
   { "name": "app_type", "label": "app_type", "query": "label_values(up,app_type)" },
   { "name": "os_type", "label": "os_type", "query": "label_values(up,os_type)" },
   { "name": "env", "label": "vcenter-env", "query": "label_values(up,env)" },
   { "name": "clustername", "label": "vcenter-clustername", "query": "label_values(up,clustername)" },
   {
    "name": "guest_fullname",
    "label": "vcenter-guest_fullname",
    "query": "label_values(up,guest_fullname)"
   },
   { "name": "esxi_hostname", "label": "vcenter-esxi_hostname", "query": "label_values(up,esxi_hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Instance Up Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance UP (Details)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==1)by(instance,alias,env,clustername,guest_fullname,esxi_hostname,app_type,env_type,os_type)"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Down Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance Down (Details)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==0)by(instance,alias,env,clustername,guest_fullname,esxi_hostname,app_type,env_type_os_type)"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"})"
    }
   ]
  },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==1)"
    }
   ]
  },
  {
   "title": "Down",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==0)"
    }
   ]
  },
  { "title": "Doahboard", "type": "dashlist", "gridPos": { "h": 6, "w": 9, "x": 11, "y": 3 } },
  {
   "title": "Instance UP status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==1) / count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"})) * 100"
    }
   ]
  },
  {
   "title": "Environment Total",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"env_type\",\"undefined\",\"env_type\",\"\"))by(env_type)",
     "legendFormat": "{{env_type}}"
    }
   ]
  },
  {
   "title": "App  Total",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"app_type\",\"undefined\",\"app_type\",\"\"))by(app_type)",
     "legendFormat": "{{app_type}}"
    }
   ]
  },
  {
   "title": "OS Total",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"os_type\",\"undefined\",\"os_type\",\"\"))by(os_type)",
     "legendFormat": "{{os_type}}"
    }
   ]
  },
  {
   "title": "instance (time series)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==1)",
     "legendFormat": "up"
    },
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==0)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "instance (time series)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==1)",
     "legendFormat": "up"
    },
    {
     "expr": "count(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"}==0)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Total Instance(group by app_type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"app_type\",\"undefined\",\"app_type\",\"\"))by(app_type)",
     "legendFormat": "{{app_type}}"
    }
   ]
  },
  {
   "title": "Current Up Status(group by app_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"app_type\",\"undefined\",\"app_type\",\"\")==1)by(app_type)",
     "legendFormat": "Up: {{app_type}}"
    },
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"app_type\",\"undefined\",\"app_type\",\"\")==0)by(app_type)",
     "legendFormat": "Down: {{app_type}}"
    }
   ]
  },
  {
   "title": "Total Instance(group by env_type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"env_type\",\"undefined\",\"env_type\",\"\"))by(env_type)",
     "legendFormat": "{{env_type}}"
    }
   ]
  },
  {
   "title": "Current Up Status(group by env_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"env_type\",\"undefined\",\"env_type\",\"\")==1)by(env_type)",
     "legendFormat": "Up: {{env_type}}"
    },
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"env_type\",\"undefined\",\"env_type\",\"\")==0)by(env_type)",
     "legendFormat": "Down: {{env_type}}"
    }
   ]
  },
  {
   "title": "Total Instance(group by os_type)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"os_type\",\"undefined\",\"os_type\",\"\"))by(os_type)",
     "legendFormat": "{{os_type}}"
    }
   ]
  },
  {
   "title": "Current Up Status(group by os_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"os_type\",\"undefined\",\"os_type\",\"\")==1)by(os_type)",
     "legendFormat": "Up: {{os_type}}"
    },
    {
     "expr": "count(label_replace(up{alias=~\"$alias.*\",env=~\"$env.*\",clustername=~\"$clustername.*\",guest_fullname=~\"$guest_fullname.*\",esxi_hostname=~\"$esxi_hostname.*\",app_type=~\"$app_type.*\",env_type=~\"$env_type.*\",os_type=~\"$os_type.*\"},\"os_type\",\"undefined\",\"os_type\",\"\")==0)by(os_type)",
     "legendFormat": "Down: {{os_type}}"
    }
   ]
  }
 ]
}