{
 "title": "Summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "app type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"app_type\",\"Others\",\"app_type\",\"\"))by(app_type)",
     "legendFormat": "{{app_type}}"
    }
   ]
  },
  {
   "title": "env type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"env_type\",\"Others\",\"env_type\",\"\"))by(env_type)",
     "legendFormat": "{{env_type}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"env\",\"Others\",\"env\",\"\"))by(env)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "os type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"os_type\",\"Others\",\"os_type\",\"\"))by(os_type)",
     "legendFormat": "{{os_type}}"
    }
   ]
  },
  {
   "title": "Guest Fullname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"guest_fullname\",\"Others\",\"guest_fullname\",\"\"))by(guest_fullname)",
     "legendFormat": "{{guest_fullname}}"
    }
   ]
  },
  {
   "title": "Linux Kernel Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(node_uname_info,\"release\",\"Others\",\"release\",\"\"))by(release)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"clustername\",\"Others\",\"clustername\",\"\"))by(clustername)",
     "legendFormat": "{{clustername}}"
    }
   ]
  },
  {
   "title": "Esxi Hostname",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(up,\"esxi_hostname\",\"Others\",\"esxi_hostname\",\"\"))by(esxi_hostname)",
     "legendFormat": "{{esxi_hostname}}"
    }
   ]
  }
 ]
}