{
 "title": "Esxi Host(vmware_exporter)",
 "description": "ESXI Host and VM information",
 "tags": [
  "prometheus",
  "vmware"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "label_values(vmware_datastore_capacity_size,ds_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "up esxi host",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "vmware_host_power_state{host_name=~\"$hostname\"}==1"
      }
     ]
    }
   ]
  },
  {
   "title": "Down Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "down esxi host",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "vmware_host_power_state{host_name=~\"$hostname\"}==0"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - vmware_host_boot_timestamp_seconds{host_name=~\"$hostname.*\"}) / count(vmware_host_boot_timestamp_seconds{host_name=~\"$hostname.*\"})"
    }
   ]
  },
  {
   "title": "Host State(Up)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_host_power_state{host_name=~\"$hostname\"}==1)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usage{host_name=~\"$hostname.*\"}) / sum(vmware_host_cpu_max{host_name=~\"$hostname.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{host_name=~\"$hostname.*\"}) / sum(vmware_host_memory_max{host_name=~\"$hostname.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(vmware_datastore_capacity_size{ds_name=~\"$datastore.*\"}) - sum(vmware_datastore_freespace_size{ds_name=~\"$datastore.*\"}))  / sum(vmware_datastore_capacity_size{ds_name=~\"$datastore.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Datastore List",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "(vmware_datastore_capacity_size - vmware_datastore_freespace_size) / vmware_datastore_capacity_size * 100",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Host State(Down)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_host_power_state{host_name=~\"$hostname\"}==0)"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usage{host_name=~\"$hostname.*\"})/1000"
    }
   ]
  },
  {
   "title": "Mem used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{host_name=~\"$hostname.*\"})"
    }
   ]
  },
  {
   "title": "DS used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_datastore_capacity_size{ds_name=~\"$datastore.*\"}) - sum(vmware_datastore_freespace_size{ds_name=~\"$datastore.*\"})"
    }
   ]
  },
  {
   "title": "CPU total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_max{host_name=~\"$hostname.*\"})/1000"
    }
   ]
  },
  {
   "title": "Mem total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 9 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{host_name=~\"$hostname.*\"})"
    }
   ]
  },
  {
   "title": "DS total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_datastore_capacity_size{ds_name=~\"$datastore.*\"})"
    }
   ]
  },
  {
   "title": "ESX Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{host_name=~\"$hostname.*\"} / vmware_host_cpu_max{host_name=~\"$hostname.*\"} * 100",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "ESX Host RAM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_memory_usage{host_name=~\"$hostname.*\"} / vmware_host_memory_max{host_name=~\"$hostname.*\"} * 100",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Datastores Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size) - (vmware_datastore_freespace_size))  / (vmware_datastore_capacity_size) * 100",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "ESX Network In/Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_transmitted_average{host_name=~\"$hostname.*\"})by(host_name)",
     "legendFormat": "{{host_name}}"
    },
    {
     "expr": "- sum(vmware_vm_net_received_average{host_name=~\"$hostname.*\"})by(host_name)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Uptime",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - vmware_vm_boot_timestamp_seconds",
       "legendFormat": "{{vm_name}}"
      }
     ]
    },
    {
     "title": "VM Power State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "vmware_vm_power_state", "legendFormat": "{{vm_name}}" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "mhz" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_cpu_usagemhz_average{host_name=~\"$hostname.*\"}",
       "legendFormat": "{{vm_name}}"
      }
     ]
    },
    {
     "title": "Number of cpu's",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_num_cpu{host_name=~\"$hostname.*\"}",
       "legendFormat": "{{vm_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_mem_usage_average{host_name=~\"$hostname.*\"}",
       "legendFormat": "{{vm_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network In/Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_net_transmitted_average{host_name=~\"$hostname\"}",
       "legendFormat": "{{vm_name}}"
      },
      {
       "expr": "- vmware_vm_net_received_average{host_name=~\"$hostname\"}",
       "legendFormat": "{{vm_name}}"
      }
     ]
    }
   ]
  }
 ]
}